import { expect, test, type Page, type TestInfo } from '@playwright/test';
import { mkdir, stat, writeFile } from 'node:fs/promises';
import path from 'node:path';

const enabled=process.env.UX_AUDIT==='1';const out=path.resolve('ux-artifacts-v3');
async function shot(page:Page,info:TestInfo,name:string,fullPage=false){await mkdir(out,{recursive:true});await page.screenshot({path:path.join(out,`${info.project.name}-${name}.png`),fullPage,animations:'disabled'});}
async function reset(page:Page){await page.goto('/');await page.evaluate(()=>localStorage.clear());await page.reload();}
async function choose(page:Page,id:'choice-a'|'choice-b'){await page.getByTestId(id).click();await page.waitForTimeout(230);}
async function metrics(page:Page){return page.evaluate(()=>{const visible=(el:Element)=>{const r=(el as HTMLElement).getBoundingClientRect();return r.width>0&&r.height>0};const buttons=[...document.querySelectorAll('button')].filter(visible).map(el=>{const r=(el as HTMLElement).getBoundingClientRect();return{text:el.textContent?.trim()??'',width:r.width,height:r.height}});return{scrollHeight:document.documentElement.scrollHeight,viewportHeight:innerHeight,overflow:document.documentElement.scrollWidth>document.documentElement.clientWidth,failedImages:[...document.images].filter(i=>i.complete&&i.naturalWidth===0).length,minButtonHeight:buttons.length?Math.min(...buttons.map(b=>b.height)):0,minButtonWidth:buttons.length?Math.min(...buttons.map(b=>b.width)):0,buttons};});}
async function quick(page:Page,info:TestInfo){const started=Date.now();await page.getByRole('button',{name:'내 반지 취향 찾기'}).click();await expect(page.locator('.header-title')).toHaveText('취향 탐색 · 1/17');await shot(page,info,'02-diagnostic-1');for(let i=0;i<17;i+=1){if(i===5){await page.getByRole('button',{name:'둘 다 비슷해요'}).click();await page.waitForTimeout(230);}else await choose(page,i%2===0?'choice-a':'choice-b');if(i===8)await shot(page,info,'03-diagnostic-10');}await expect(page.locator('.header-title')).toHaveText('16강 · 1/8');await shot(page,info,'04-quick-16');let round=16;for(let i=0;i<15;i+=1){await choose(page,i%3===0?'choice-b':'choice-a');if(i===14)break;const text=(await page.locator('.header-title').textContent({timeout:2000}))??'';const current=Number(text.match(/(\d+)강/)?.[1]??round);if(current!==round&&[8,4,2].includes(current)){round=current;await shot(page,info,`05-round-${current}`);}}await expect(page).toHaveURL(/\/result/);await expect(page.getByText('반지샵에서 이렇게 말해보세요')).toBeVisible();return Date.now()-started;}

test.describe('production UX audit v3',()=>{test.skip(!enabled,'UX_AUDIT=1 only');
 test('complete real mobile journey',async({page,context},info)=>{const consoleErrors:string[]=[];page.on('console',m=>{if(m.type()==='error')consoleErrors.push(m.text())});page.on('pageerror',e=>consoleErrors.push(`pageerror:${e.message}`));await reset(page);await shot(page,info,'01-landing',true);const landing=await metrics(page);expect(landing.overflow).toBeFalsy();expect(landing.failedImages).toBe(0);const quickElapsedMs=await quick(page,info);await shot(page,info,'06-result-top');await shot(page,info,'07-result-full',true);const result=await metrics(page);expect(result.overflow).toBeFalsy();expect(result.failedImages).toBe(0);await page.getByRole('button',{name:'착용 모습'}).click();await expect(page.getByAltText('내 취향 우승 반지 착용 이미지')).toBeVisible();await shot(page,info,'08-result-worn');await page.getByRole('button',{name:'반지만'}).click();await context.grantPermissions(['clipboard-read','clipboard-write']);await page.getByRole('button',{name:'문장 복사'}).click();await expect(page.getByText('매장용 문장을 복사했어요.')).toBeVisible();const dl=page.waitForEvent('download');await page.getByRole('button',{name:'결과 이미지 저장'}).click();const download=await dl;const p=await download.path();const downloadBytes=p?(await stat(p)).size:0;expect(downloadBytes).toBeGreaterThan(20_000);await page.getByRole('button',{name:'다시 취향 찾기'}).click();await expect(page.getByRole('dialog')).toBeVisible();await shot(page,info,'09-restart-sheet');await page.getByRole('button',{name:'취소'}).click();const final=await metrics(page);const tooSmall=final.buttons.filter(b=>b.height<44||b.width<44);expect(tooSmall,JSON.stringify(tooSmall)).toEqual([]);expect(consoleErrors).toEqual([]);await writeFile(path.join(out,`${info.project.name}-metrics.json`),JSON.stringify({project:info.project.name,viewport:page.viewportSize(),quickElapsedMs,downloadBytes,landing,result,consoleErrors},null,2));});
 test('refresh undo resume',async({page},info)=>{await reset(page);await page.getByRole('button',{name:'내 반지 취향 찾기'}).click();for(let i=0;i<6;i+=1)await choose(page,i%2?'choice-a':'choice-b');await page.reload();await expect(page.locator('.header-title')).toHaveText('취향 탐색 · 7/17');await page.getByRole('button',{name:'이전 선택으로 돌아가기'}).click();await expect(page.locator('.header-title')).toHaveText('취향 탐색 · 6/17');await page.goBack();await expect(page.getByRole('button',{name:/이어서 하기/})).toBeVisible();await shot(page,info,'10-resume');});
 test('64 mode 63 taps',async({page},info)=>{test.skip(info.project.name!=='mobile-390');await reset(page);const started=Date.now();await page.getByRole('button',{name:'64강으로 끝까지 고르기'}).click();await expect(page.locator('.header-title')).toHaveText('64강 · 1/32');await shot(page,info,'11-full-64');for(let i=0;i<63;i+=1){await choose(page,i%4===0?'choice-b':'choice-a');if(i===31)await shot(page,info,'12-full-after-64');if(i===47)await shot(page,info,'13-full-after-32');if(i===55)await shot(page,info,'14-full-after-16');if(i===61)await shot(page,info,'15-full-final');}await expect(page).toHaveURL(/\/result/);await writeFile(path.join(out,'mobile-390-full-metrics.json'),JSON.stringify({elapsedMs:Date.now()-started},null,2));});
});
